{% set name = "climatecontrol" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/climatecontrol-{{ version }}.tar.gz
  sha256: ee3c84a452c301da7e8d23d2cc0d73c9e679d2a849d7c7843055f65e564d37a8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core >=1.0.0,<2.0.0
    - pytest-runner
  run:
    - python >=3.6
    - wrapt

test:
  imports:
    - climatecontrol
    - climatecontrol.ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/daviskirk/climatecontrol
  summary: Python library for loading app configurations from files and/or namespaced environment variables
  description: |
    CLIMATECONTROL controls your applications settings and configuration environment. It is a Python library for loading app configurations from files and/or namespaced environment variables.

    Features
      * Separation of settings and code
      * Loading from files (.yaml, .json, .toml)
      * Loading multiple files using glob syntax
      * Loading from environment variables, including loading of nested values
      * Freely reference nested configurations via files or environment variables
      * CLI integration
      * Validation using the Validation library of your choice
      * Logging configuration integration
      * Testing integration
  dev_url: https://github.com/daviskirk/climatecontrol
  doc_url: https://github.com/daviskirk/climatecontrol
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daviskirk
